# Generated by Django 5.1.2 on 2024-10-31 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_room_exam_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Imtahan', 'verbose_name_plural': 'Imtahanlar'},
        ),
        migrations.AlterModelOptions(
            name='examtype',
            options={'verbose_name': 'İmtahan növü', 'verbose_name_plural': 'İmtahan növü'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Mərtəbə', 'verbose_name_plural': 'Mərtəbələr'},
        ),
        migrations.AlterModelOptions(
            name='grader',
            options={'verbose_name': 'Sinif', 'verbose_name_plural': 'Siniflər'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Bilet', 'verbose_name_plural': 'Biletlər'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.floor', verbose_name='Mərtəbə'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.TimeField(verbose_name='Saat'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.exam', verbose_name='İmtahan'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='grades',
            field=models.ManyToManyField(to='ticket.grader', verbose_name='Siniflər'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mərtəbə adı'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='precinct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.precinct', verbose_name='Məntəqə'),
        ),
        migrations.AlterField(
            model_name='grader',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Sinif'),
        ),
        migrations.AlterField(
            model_name='precinct',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='precinct',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.exam', verbose_name='İmtahan'),
        ),
        migrations.AlterField(
            model_name='precinct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_seats',
            field=models.IntegerField(verbose_name='Böş yer sayı'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='Yer sayı'),
        ),
        migrations.AlterField(
            model_name='room',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.examtype', verbose_name='İmtahan növü'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.floor', verbose_name='Mərtəbə'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.exam', verbose_name='İmtahan'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.examtype', verbose_name='İmtahan növü'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='gender',
            field=models.CharField(choices=[('M', 'Kişi'), ('F', 'Qadın')], max_length=5, verbose_name='Cinsiyyət'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='grader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.grader', verbose_name='Sinif'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='precinct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.precinct', verbose_name='Məntəqə'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.room', verbose_name='Otaq'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='school',
            field=models.CharField(max_length=100, verbose_name='Məktəb'),
        ),
    ]
