# Generated by Django 5.1.2 on 2024-10-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_exam_options_alter_examtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Məkan nömrəsi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Boş')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='ticket.room', verbose_name='Otaq')),
            ],
            options={
                'verbose_name': 'Yer',
                'verbose_name_plural': 'Yerlər',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.seat', verbose_name='Yer'),
        ),
    ]
