# Generated by Django 5.1.2 on 2024-10-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_options_seat_ticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Bilet', 'verbose_name_plural': 'Biletlər'},
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
