# Generated by Django 5.1.2 on 2024-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticket_seat_alter_ticket_options_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yer nömrəsi'),
        ),
    ]
