# Generated by Django 5.1.2 on 2024-10-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
    ]
