# Generated by Django 5.1.2 on 2024-11-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_remove_ticket_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupied_seats',
            field=models.JSONField(default=list, verbose_name='Zanıyətli yerlər'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(default=1, verbose_name='Номер места'),
            preserve_default=False,
        ),
    ]
