# Generated by Django 5.1.2 on 2024-11-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_room_occupied_seats_ticket_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupied_seats',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
    ]
