# Generated by Django 5.1.2 on 2024-11-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_remove_room_occupied_seats_remove_ticket_seat_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precinct',
            options={'verbose_name': 'Məntəqə', 'verbose_name_plural': 'Məntəqələr'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Otaq', 'verbose_name_plural': 'Otaqlar'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='İş nömrə'),
        ),
    ]
