# Generated by Django 5.1.2 on 2024-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_seat_ticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yer nömrəsi'),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_seats',
            field=models.IntegerField(default=0, verbose_name='Böş yer sayı'),
        ),
    ]
